resources:
  - crds/customresourcedefinition.yaml
  - appproject.yaml
  - clusterrole.yaml
  - configmap.yaml
  - deployment.yaml
  - networkpolicy.yaml
  - role.yaml
  - secret.yaml
  - service.yaml
  - serviceaccount.yaml
  - statefulset.yaml
  - nginx-test-deploy.yaml
