apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-self-manage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jieun-14/argocd-cicd.git
    targetRevision: main
    path: manifests/overlays/md
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
