apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: cicd-tools
spec:
  destination:
    namespace: cicd-tools
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/argocd
    repoURL: https://github.com/kt-cloud-stack/admin-dev-cluster.git
    targetRevision: HEAD
