apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: {{ .Values.argocd.namespace }}
spec:
  project: default
  source:
    repoURL: https://github.com/kt-cloud-stack/admin-dev-cluster.git
    targetRevision: HEAD
    path: manifests/charts
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.argocd.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
