apiVersion: v1
data:
  policy.csv: |2

    ## Github Teams to Argocd groups role
    g, kt-cloud-stack:admin, role:admin
    g, kt-cloud-stack:maintainer, role:maintainer
    g, kt-cloud-next:admin, role:admin
    g, kt-cloud-next:platform-development, role:svc-dev-devops
    g, kt-cloud-next:ui-ux, role:svc-dev-front

    ## Argocd group role - maintainer
    p, role:maintainer, clusters, get, *, allow
    p, role:maintainer, repositories, *, *, allow
    p, role:maintainer, projects, *, *, allow
    p, role:maintainer, gpgkeys, *, *, allow
    p, role:maintainer, certificates, *, *, allow
    p, role:maintainer, extensions, *, *, allow
    p, role:maintainer, logs, *, *, allow
    p, role:maintainer, exec, *, *, allow
    p, role:maintainer, applications, *, *, allow
    p, role:maintainer, applicationsets, *, *, allow


    ## Argocd group role - ns-devops maintainer
    p, role:svc-dev-devops, clusters, get, *, allow
    p, role:svc-dev-devops, repositories, *, *, allow
    p, role:svc-dev-devops, projects, get, *, allow
    p, role:svc-dev-devops, gpgkeys, *, *, allow
    p, role:svc-dev-devops, certificates, *, *, allow
    p, role:svc-dev-devops, extensions, *, *, allow
    p, role:svc-dev-devops, logs, *, devops/*, allow
    p, role:svc-dev-devops, exec, *, devops/*, allow
    p, role:svc-dev-devops, applications, *, devops/*, allow
    p, role:svc-dev-devops, applicationsets, *, devops/*, allow

    ## Argocd group role - ns-front maintainer
    p, role:svc-dev-front, clusters, get, *, allow
    p, role:svc-dev-front, repositories, *, *, allow
    p, role:svc-dev-front, projects, get, *, allow
    p, role:svc-dev-front, gpgkeys, *, *, allow
    p, role:svc-dev-front, certificates, *, *, allow
    p, role:svc-dev-front, extensions, *, *, allow
    p, role:svc-dev-front, logs, *, front/*, allow
    p, role:svc-dev-front, exec, *, front/*, allow
    p, role:svc-dev-front, applications, *, front/*, allow
    p, role:svc-dev-front, applicationsets, *, front/*, allow
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"argocd-rbac-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-rbac-cm","namespace":"cicd-tools"}}
  creationTimestamp: "2025-01-09T04:16:54Z"
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: cicd-tools
  resourceVersion: "25538710"
  uid: 8b8a21ef-7dca-433b-b6b3-4368cf49599f
